---
apiVersion: apps/v1   # use apps/v1beta2 for versions before 1.9.0
kind: Deployment
metadata:
  name: add-torrent-deployment
spec:
  selector:
    matchLabels:
      app: add-torrent
  replicas: 1
  template:
    metadata:
      labels:
        app: add-torrent
    spec:
      containers:
        - name: add-torrent
          image: jeffbr13/add-torrent
          ports:
            - containerPort: 3000
          env:
            # configure ConfigMap
            - name: TRANSMISSION_RPC_URL
              valueFrom:
                configMapKeyRef:
                  name: add-torrent-config
                  key: transmission-rpc-url
            - name: DOWNLOAD_DIRECTORIES
              valueFrom:
                configMapKeyRef:
                  name: add-torrent-config
                  key: download-directories

---
kind: Service
apiVersion: v1
metadata:
  name: add-torrent-service
spec:
  selector:
    app: add-torrent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: add-torrent-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: add-torrent.jeffbr13.net
      http:
        paths:
          - path:
            backend:
              serviceName: add-torrent-service
              servicePort: 80
