---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "add-torrent.fullname" . }}
  labels:
    app: {{ template "add-torrent.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  transmission-rpc-url: {{ default "" .Values.transmissionRpcUrl | quote }}
  download-directories: {{ default "" .Values.downloadDirectories | quote }}
